import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="text-center">
          <div className="flex justify-center items-center h-3/6">
            <Image
              className="max-w-full h-auto"
              src="/images/hplus-logo.png"
              alt="Hplus Logo"
              width={500}
              height={200}
            />
            <h1 className="text-5xl">Knowledge Base</h1>
          </div>
          <h1>Navbar</h1>
        </header>

        
        <div className="h-[calc(100vh-5rem)]">{children}</div>
      </body>
    </html>
  );
}
